;
; Dev/SBC-386EX/SBC-386EX.inc
;

; These are the definitions for the specific SBC-386EX devices

;-------------------------------------------------------------------------------
%include        "Dev/SBC-386EX/FPU.inc"        ; Definitions for GPIO ports
;-------------------------------------------------------------------------------
%include        "Dev/SBC-386EX/Lite.inc"       ; Definitions for GPIO ports
;-------------------------------------------------------------------------------
%include        "Dev/SBC-386EX/RTC.inc"        ; Definitions for GPIO ports
;-------------------------------------------------------------------------------
%include        "Dev/SBC-386EX/SDCard.inc"     ; Definitions for GPIO ports
;-------------------------------------------------------------------------------
%include        "Dev/SBC-386EX/IDE.inc"        ; Definitions for GPIO ports
;-------------------------------------------------------------------------------
