;
; Dev/SBC-386EX/SBC-386EX.inc
;

; These are the definitions for the specific SBC-386EX devices

;-------------------------------------------------------------------------------
%include        "Dev/SBC-386EX/Defn.inc"       ; The main board hardware
;-------------------------------------------------------------------------------
%include        "Dev/SBC-386EX/FPU.inc"        ; Floating Point Unit detect
;-------------------------------------------------------------------------------
%include        "Dev/SBC-386EX/Lite.inc"       ; General Purpose Input/Output ports
;-------------------------------------------------------------------------------
%include        "Dev/SBC-386EX/RTC.inc"        ; Real Time Clock chip
;-------------------------------------------------------------------------------
%include        "Dev/SBC-386EX/SDCard.inc"     ; Secure Data Card
;-------------------------------------------------------------------------------
%include        "Dev/SBC-386EX/IDE.inc"        ; Integrated Drive Electronics port
;-------------------------------------------------------------------------------
%include        "Dev/SBC-386EX/VGA3.inc"       ; Video Graphics Array 3 card
;-------------------------------------------------------------------------------
